import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import SidebarComponent from "@/components/SidebarComponent";

const manrope = Manrope({
  weight: ["400", "500", "700"],
  display: "swap",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <SidebarComponent />
      <main className=" p-12 w-full">
        <html
          lang="pt-br"
          suppressHydrationWarning
          className={manrope.className}
        >
          <body>{children}</body>
        </html>
      </main>
    </SidebarProvider>
  );
}
